## NOTE: if you are not going to add any elements to this list, then remove the list name as well.
exclusionList:
- java/
- sun
- apple/
- com/apple
- com/sun
- sunw
- sun
- javax/
- org/ietf
- org/jcp
- org/omg
- org/w3c
- org/xml
- org/objectweb/asm
- edu/uci/spiderlab/analysis
- org/spideruci/analysis
- test/
- Core/
- Data/
- dacapo
- Harness
- org/mockito
- org/hamcrest
- junit
- org/junit
- org/fest
- junit/tests/framework/
- junit/tests/runner/TextFeedbackTest
- junit/tests/runner/TextRunnerTest
- junit/tests/extensions

## NOTE: if you are not going to add any elements to this list, then remove the list name as well.
inclusionList:
- org/apache/commons/pool2
# - org/apache/commons/net
# - org/apache/commons/jexl3
# - org/apache/commons/imaging
# - org/apache/commons/jxpath
# - org/apache/commons/validator
# - org/apache/commons/compress
# - org/apache/xmlgraphics
# - com/google/gson
# - com/fasterxml/jackson/dataformat/xml
# - com/fasterxml/jackson/databind
# - com/fasterxml/jackson/core
# - org/apache/commons/configuration2
# - org/apache/commons/csv
# - org/apache/commons/lang3
# - org/apache/commons/collections4
# - org/apache/commons/codec
# - org/jfree
# - org/apache/commons/text
# - org/apache/commons/io
# - org/apache/commons/cli
# - org/jsoup
# - nl/tudelft/jpacman
# - org/joda
# - com/alibaba/fastjson

# - hyr/blinky
# - java/
# - javax/
# - org/ietf
# - org/jcp
# - org/omg
# - org/w3c
# - org/xml
# - sun/

# - org/spideruci/patternabstraction/benckmark
# - org/spideruci/analysis/diagnostics/subjects
# - java/util/ArrayList
# - java/util/Vector
# - java
# - sun
# - apple/
# - com/apple
# - com/sun
# - com/oracle
# - org/ietf
# - org/jcp
# - org/omg
# - org/w3c
# - org/xml

retransformInclusionList:
- java/
- javax/
- org/ietf
- org/jcp
- org/omg
- org/w3c
- org/xml
# - sun/
# - java/util/Vector
# - java
# - sun
# - apple/
# - com/apple
# - com/sun
# - com/oracle
# - org/ietf
# - org/jcp
# - org/omg
# - org/w3c
# - org/xml

## FUTURE EXAMPLES (NOT YET TESTED; DO NOT UNCOMMENT):
# name: blinky
# number: !!int 1
# float: !!float 1.0
# boolen: !!bool true
# array: [1]
# LINE_COUNT: !!float 0.0